name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: "14"
      # - run: npm install -g bats
      # - run: cat file_not_exists || true
      # - run: cat file_not_exists
      # - run: bats -v
      - run: bash -x ./make.sh test0
      - run: ./make.sh test1
      - run: ./make.sh test2
      - run: echo 'supposed not seeing this since previous step will exit'
